apiVersion: app/v1
kind: Deployment
metadata: 
  name: frontend-deployment
spec: 
  selector: 
    matchLabels: 
      app: frontend
  replicas: 1
  template: 
    metadata: 
      labels:
        app: frontend
    spec: 
      containers: 
        - name: frontend
          image: frontend:latest
          ports:
            - containerPort: 80
