apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
spec: 
  selector: 
    matchLabels: 
      app: frontend
  replicas: 1
  template: 
    metadata: 
      labels:
        app: frontend
    spec: 
      imagePullSecrets:
        - name: regcred
      containers: 
        - name: frontend
          image: 124355654427.dkr.ecr.ap-south-1.amazonaws.com/frontend/service:20250416163120
          ports:
            - containerPort: 83
          resources: 
            requests: 
              memory: "128Mi"
              cpu: "250m"
            limits: 
              memory: "256Mi"
              cpu: "500m"
