apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
  namespace: disaster-relief
spec: 
  selector: 
    matchLabels: 
      app: frontend
  replicas: 1
  template: 
    metadata: 
      labels:
        app: frontend
    spec: 
      imagePullSecrets:
        - name: ecr-creds
      containers: 
        - name: frontend
          image: 124355654427.dkr.ecr.ap-south-1.amazonaws.com/frontend/service:20250416123037
          ports:
            - containerPort: 80
