pipeline {
    agent any

    environment {
        AWS_CREDENTIALS = credentials('aws-ecr-credentials')  // Use Jenkins credentials
        IMAGE_NAME = 'frontend-ecr-repo'
        AWS_REGION = 'ap-south-1'  // Change to your AWS region
        ACCOUNT_ID = '124355654427'  // Replace with your AWS Account ID
        ECR_URL = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'github-credentials', url: 'https://github.com/Rishavkapil/disaster-relief-app.git', branch: 'main'
            }
        }

        stage('Login to AWS ECR') {
            steps {
                script {
                    sh '''
                    aws ecr get-login-password --region $AWS_REGION --profile=124355654427| docker login --username AWS --password-stdin $ECR_URL
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh '''
                    docker build -t $IMAGE_NAME .
                    '''
                }
            }
        }

        stage('Tag and Push Image to ECR') {
            steps {
                script {
                    sh '''
                    docker tag $IMAGE_NAME:latest $ECR_URL:latest
                    docker push $ECR_URL:latest
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Docker image successfully pushed to ECR!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}

