version: '3.8'

services:
  backend:
    image: rishavkapil/backend  # Ensure this is the correct backend image ID or tag
    container_name: backend-container
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://rishavkapil:this_is_my_password_1@my-cluster.rcmvs.mongodb.net/?retryWrites=true&w=majority&appName=my-cluster
      - FRONTEND_URL=http://frontend:3000
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend  # Ensure the Dockerfile is inside ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://backend:5000/api/
    container_name: frontend-container
    restart: always
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000/api/
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

